name: caddy
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    restart: unless-stopped
    environment:
      CADDY_INGRESS_NETWORKS: caddy
    labels:
      caddy.respond: / "unknown docker subdomain" 404
    ports:
    - 8080:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - caddy
networks:
  caddy:
    external: true