services:

  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    restart: unless-stopped
    command: --port=1986 --name="CozyLab" --persist
    user: "1000:1000"
    labels:
      caddy: http://books.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 1986}}"
    volumes:
    - /mnt/jellyfin/books:/books/books
    expose:
    - 1986
    networks:
    - caddy

networks:
  caddy:
    external: true
