name: servarr
services:

  sonarr:
    user: 3000:3000
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
    - PUID=3000
    - PGID=3000
    - TZ=America/New_York
    labels:
      caddy: http://sonarr.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 8989}}"
    volumes:
    - /data/servarr/sonarr:/config
    - /mnt/spirit-library/media:/mnt/spirit-library/media:rw,nosuid,noexec,nodev
    expose:
    - 8989
    networks:
    - caddy

  radarr:
    user: 3000:3000
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
    - PUID=3000
    - PGID=3000
    - TZ=America/New_York
    labels:
      caddy: http://radarr.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 7878}}"
    volumes:
    - /data/servarr/radarr:/config
    - /mnt/spirit-library/media:/mnt/spirit-library/media:rw,nosuid,noexec,nodev
    expose:
    - 7878
    networks:
    - caddy

  prowlarr:
    user: 3000:3000
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
    - PUID=3000
    - PGID=3000
    - TZ=America/New_York
    labels:
      caddy: http://prowlarr.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 9696}}"
    volumes:
    - /data/servarr/prowlarr:/config
    expose:
    - 9696
    networks:
    - caddy

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
    - TZ=America/New_York
    labels:
      caddy: http://jellyseerr.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 5055}}"
    volumes:
    - /data/servarr/jellyseerr:/app/config
    expose:
    - 5055
    networks:
    - caddy

  sabnzbd:
    user: 3000:3000
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
    - PUID=3000
    - PGID=3000
    - TZ=America/New_York
    labels:
      caddy: http://sabnzbd.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
    - /data/servarr/sabnzbd:/config
    - /mnt/spirit-library/media:/mnt/spirit-library/media:rw,nosuid,noexec,nodev
    expose:
    - 8080
    networks:
    - caddy

  qbittorrent:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    environment:
    - VPN_ENABLED=yes
    - VPN_PROV=custom
    - VPN_CLIENT=wireguard
    - LAN_NETWORK=100.115.0.0/24
    - DEBUG=false
    - WEBUI_PORT=8080
    - UMASK=002
    - PUID=3000
    - PGID=3000
    labels:
      caddy: http://qbittorrent.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
    - /data/servarr/qbittorrent:/config:rw,nosuid,noexec,nodev
    - /mnt/spirit-library/media:/mnt/spirit-library/media:rw,nosuid,noexec,nodev
    expose:
    - 8080
    networks:
    - caddy

networks:
  caddy:
    external: true
