name: servarr
services:

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    labels:
      caddy: sonarr.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8989}}"
    volumes:
    - /data/stacks/servarr/sonarr:/config
    - /data/stacks/servarr/sabnzbd/Downloads/complete:/config/Downloads/complete
    - /mnt/jellyfin:/mnt/jellyfin
    expose:
    - 8989
    networks:
    - caddy

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    labels:
      caddy: radarr.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 7878}}"
    volumes:
    - /data/stacks/servarr/radarr:/config
    - /data/stacks/servarr/sabnzbd/Downloads/complete:/config/Downloads/complete
    - /mnt/jellyfin:/mnt/jellyfin
    expose:
    - 7878
    networks:
    - caddy

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    labels:
      caddy: prowlarr.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 9696}}"
    volumes:
    - /data/stacks/servarr/prowlarr:/config
    expose:
    - 9696
    networks:
    - caddy

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    labels:
      caddy: jellyseerr.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 5055}}"
    volumes:
    - /data/stacks/servarr/jellyseerr:/app/config
    expose:
    - 5055
    networks:
    - caddy

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    labels:
      caddy: sabnzbd.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
    - /data/stacks/servarr/sabnzbd:/config
    - /mnt/jellyfin:/mnt/jellyfin
    expose:
    - 8080
    networks:
    - caddy

networks:
  caddy:
    external: true
