name: portainer
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.rule=Host(`portainer.docker.den`)"
    - "traefik.http.routers.portainer.entrypoints=web" # Use the "web" entrypoint
    - "traefik.http.services.portainer.loadbalancer.server.port=9000" # Target the correct internal port
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    networks:
    - traefik
networks:
  traefik:
    external: true
