name: portainer
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    labels:
      caddy: portainer.docker.den
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    networks:
    - caddy
networks:
  caddy:
    external: true
