name: portainer
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    labels:
      caddy: http://docker.cozy-lab.dev
      caddy.reverse_proxy: "{{upstreams 9000}}"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/portainer:/data
    networks:
    - caddy
networks:
  caddy:
    external: true
